// web/frontend/src/app/components/command-sender/command-sender.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CosmosApiService, GetCmdParamListItem } from '../../services/cosmos-api.service';
import { CmdParamValAndStates, CmdParam } from './command-parameter-editor.component';
import { Observable } from "rxjs/Observable";

@Component({
  selector: 'cosmos-command-sender',
  templateUrl: './command-sender.component.html',
  styleUrls: ['./command-sender.component.css']
})
export class CommandSenderComponent implements OnInit {

  targetName:string = '';
  commandName:string = '';
  ignoreRangeChecks:boolean = false;
  ignoreRangeChecksIcon = 'fa-circle-o';
  showIgnoredParams:boolean = false;
  showIgnoredParamsIcon = 'fa-circle-o';
  ignoredParams:string[] = [];
  rows:CmdParam[] = [];
  interfaces = [];
  selectedInterface = '';
  rawCmdFile = null;
  menuItems = [];
  status:string = '';
  displaySendHazardous:boolean = false;
  displayErrorDialog:boolean = false;
  displaySendRaw:boolean = false;
  sendDisabled:boolean = true;

  constructor(private api: CosmosApiService) { }

  buildMenu() {
    var fileMenuItems = {
      label: 'File', items:
        [
          {label: 'Send Raw',
           command: () => {this.setupRawCmd()} }
        ]
    };

    var modeMenuItems = {
      label: 'Mode', items:
      [
        {label: 'Ignore Range Checks',
         icon: this.ignoreRangeChecksIcon,
         command: () => {this.toggleIgnoreRangeChecks()} },
        {label: 'Show Ignored Parameters',
         icon: this.showIgnoredParamsIcon,
         command: () => {this.toggleShowIgnoredParams()} },
      ]
    };
    this.menuItems = [fileMenuItems, modeMenuItems];
  }

  toggleIgnoreRangeChecks() {
    if (this.ignoreRangeChecks == false) {
      this.ignoreRangeChecks = true;
      this.ignoreRangeChecksIcon = 'fa-check-circle-o';
      this.buildMenu();
    }
    else {
      this.ignoreRangeChecks = false;
      this.ignoreRangeChecksIcon = 'fa-circle-o';
      this.buildMenu();
    }
  }

  toggleShowIgnoredParams() {
    if (this.showIgnoredParams == false) {
      this.showIgnoredParams = true;
      this.showIgnoredParamsIcon = 'fa-check-circle-o';
      this.buildMenu();
    }
    else {
      this.showIgnoredParams = false;
      this.showIgnoredParamsIcon = 'fa-circle-o';
      this.buildMenu();
    }
    this.updateCmdParams();
  }

  ngOnInit() {
    this.buildMenu();    
  }

  isFloat(str) {
    // Regex to identify a string as a floating point number
    if (/^\s*[-+]?\d*\.\d+\s*$/.test(str)) {
      return true;
    }
    // Regex to identify a string as a floating point number in scientific notation. 
    if (/^\s*[-+]?(\d+((\.\d+)?)|(\.\d+))[eE][-+]?\d+\s*$/.test(str)) {
      return true;
    }
    return false;
  }

  isInt(str) {
    // Regular expression to identify a String as an integer
    if (/^\s*[-+]?\d+\s*$/.test(str)) {
      return true;
    }

    // # Regular expression to identify a String as an integer in hexadecimal format
    if (/^\s*0[xX][\dabcdefABCDEF]+\s*$/.test(str)) {
      return true;
    }
    return false;
  }

  isArray(str) {
    // Regular expression to identify a String as an Array
    if (/^\s*\[.*\]\s*$/.test(str)) {
      return true;
    }
    return false;
  }

  removeQuotes(str) {
    // Return the string with leading and trailing quotes removed
    if (str.length < 2) {
      return str;
    }
    var firstChar = str.charAt(0);
    if ((firstChar != '"') && (firstChar != "'")) {
      return str;
    }
    var lastChar = str.charAt(str.length-1);
    if (firstChar != lastChar) {
      return str;
    }
    return str.slice(1, -1);
  }

  convertToValue(param:CmdParam) {
    if (typeof param.val_and_states.val != 'string')
    {
      return param.val_and_states.val;
    }

    var str = param.val_and_states.val;
    var quotes_removed = this.removeQuotes(str);
    if (str == quotes_removed) {
      var upcaseStr = str.toUpperCase();
    
      if (((param.type == "STRING") || (param.type == "BLOCK")) && upcaseStr.startsWith("0X")) {
        var hexStr = upcaseStr.slice(2);
        if ((hexStr.length % 2) != 0) {
          hexStr = "0" + hexStr;
        }
        var jstr = {"json_class":"String", "raw":[]}
        for (var i = 0; i < hexStr.length; i += 2) {
          var nibble = hexStr.charAt(i) + hexStr.charAt(i+1);
          jstr.raw.push(parseInt(nibble, 16));
        }
        return jstr;
      }
      else {
        if (upcaseStr == 'INFINITY') {
          return Infinity;
        }
        else if (upcaseStr == '-INFINITY') {
          return -Infinity;
        }
        else if (upcaseStr == 'NAN') {
          return NaN;
        }
        else if (this.isFloat(str)) {
          return parseFloat(str);
        }
        else if (this.isInt(str)) {
          return parseInt(str);
        }
        else if (this.isArray(str)) {
          return eval(str)
        }
        else {
          return str;
        }
      }
    }
    else {
      return quotes_removed;
    }
  }

  convertToString(value) {
    var return_value = ''
    if (Object.prototype.toString.call(value).slice(8, -1) === 'Array') {
      var arrayLength = value.length;
      return_value = '[ ';
      for (var i = 0; i < arrayLength; i++) {
        if (Object.prototype.toString.call(value[i]).slice(8, -1) === 'String') {
          return_value += '"' + value[i] + '"';
        } else {
          return_value += value[i];
        }
        if (i != (arrayLength - 1)) {
          return_value += ', ';
        }
      }
      return_value += ' ]'
    }
    else if (Object.prototype.toString.call(value).slice(8, -1) === 'Object') {
      if (value.json_class == "String" && value.raw) {
        // This is binary data, display in hex.
        return_value = '0x'
        for (var i = 0; i < value.raw.length; i++) {
          var nibble = value.raw[i].toString(16).toUpperCase();
          if (nibble.length < 2) {
            nibble = "0" + nibble;
          }
          return_value += nibble;
        }
      }
      else if (value.json_class == "Float" && value.raw) {
        return_value = value.raw;
      }
      else {
        // TBD - are there other objects that we need to handle?
        return_value = String(value);
      }
    }
    else {
      return_value = String(value);
    }
    return return_value;
  }

  commandChanged(event) {
    this.targetName = event.targetName;
    this.commandName = event.commandName;
    this.updateCmdParams();
  }

  updateCmdParams() {
    this.sendDisabled = true;
    this.ignoredParams = []
    this.rows = []
    this.status = "Attempting to get ignored parameters from server...";
    this.api.get_target_ignored_parameters(this.targetName).retry().subscribe(
    (ignoredParams) => {
      this.ignoredParams = ignoredParams;
      this.status = "Attempting to get command parameters from server...";
      this.api.get_cmd_param_list(this.targetName, this.commandName).retry().subscribe(
      (data:GetCmdParamListItem[]) => {
        for (var i = 0; i < data.length; i++)
        {
          if (!this.ignoredParams.includes(data[i][0]) || this.showIgnoredParams) {
            this.rows.push({
              parameter_name : data[i][0],
              val_and_states : {val: this.convertToString(data[i][1]), states: data[i][2], selected_state: null, selected_state_label: '', manual_value: null},
              description    : data[i][3],
              units          : data[i][5],
              type           : data[i][7],
            });
          }
        }
        this.sendDisabled = false;
        this.status = '';
      },
      (error) => {
        this.displayError('getting command parameters', error);
      });
    },
    (error) => {
      this.displayError('getting ignored parameters', error);
    });
  }

  statusChange(event) {
    this.status = event.status;
  }
  
  sendCmd(event) {
    var paramList = {};
    for (var i = 0; i < this.rows.length; i++)
    {
      paramList[this.rows[i].parameter_name] = this.convertToValue(this.rows[i]);
    }

    var hazardous = false;
    this.api.get_cmd_hazardous(this.targetName, this.commandName, paramList).subscribe (
    (response) => {
      hazardous = response;
    
      if (hazardous) {
        this.displaySendHazardous = true;
      }
      else {
        var obs;
        if (this.ignoreRangeChecks) {
          obs = this.api.cmd_no_range_check(this.targetName, this.commandName, paramList);
        }
        else {
          obs = this.api.cmd(this.targetName, this.commandName, paramList);
        }

        obs.subscribe(
        (response) => {
          this.processCmdResponse(true, response);
        },
        (error) => {
          this.processCmdResponse(false, error);
        });
      }
    },
    (error) => {
      this.processCmdResponse(false, error);
    });
  }

  sendHazardousCmd(event) {
    this.displaySendHazardous = false;
    var paramList = {};
    for (var i = 0; i < this.rows.length; i++)
    {
      paramList[this.rows[i].parameter_name] = this.convertToValue(this.rows[i]);
    }

    var obs;
    if (this.ignoreRangeChecks) {
      obs = this.api.cmd_no_checks(this.targetName, this.commandName, paramList);
    }
    else {
      obs = this.api.cmd_no_hazardous_check(this.targetName, this.commandName, paramList);
    }

    obs.subscribe(
    (response) => {
      this.processCmdResponse(true, response);
    },
    (error) => {
      this.processCmdResponse(false, error);
    });
  }

  cancelHazardousCmd(event) {
    this.displaySendHazardous = false;
    this.status = 'Hazardous command not sent';
  }

  processCmdResponse(cmd_sent, response) {
    var msg = '';
    if (cmd_sent) {
      msg += 'cmd("' + response[0] + " " + response[1];
      var keys = Object.keys(response[2]);
      if (keys.length > 0) {
        msg += " with ";
        for (var i = 0; i < keys.length; i++) {
          var key = keys[i];
          msg += key + " " + this.convertToString(response[2][key]);
          if (i < keys.length-1) {
            msg += ", ";
          }
        }
      }
      msg += '") sent.'
      
      this.status = msg;
    }
    else {
      var context = 'sending ' + this.targetName + ' ' + this.commandName;
      this.displayError(context, response, true);
    }
  }

  displayError(context, error, showDialog=false) {
    this.status = 'Error ' + context + ' due to ' + error.name;
    if (error.message && error.message != "") {
      this.status += ': ';
      this.status += error.message;
    }
    if (showDialog) {
      this.displayErrorDialog = true
    }
  }

  ackError(event) {
    this.displayErrorDialog = false;
  }

  setupRawCmd() {
    this.api.get_interface_names().subscribe (
    (response) => {
      var interfaces = []
      for (var i = 0; i < response.length; i++) {
        interfaces.push({label: response[i], value: response[i]})
      }
      this.interfaces = interfaces;
      this.selectedInterface = interfaces[0].value;
      this.displaySendRaw = true;
    },
    (error) => {
      this.displaySendRaw = false;
      this.displayError("getting interface names", error, true);
    });
  }

  selectRawCmdFile(event) {
    this.rawCmdFile = event.target.files[0];
  }

  onLoad(event) {
    var bufView = new Uint8Array(event.target.result)
    var jstr = {"json_class":"String", "raw":[]}
    for (var i = 0; i < bufView.length; i++) {
      jstr.raw.push(bufView[i]);
    }
      
    this.api.send_raw(this.selectedInterface, jstr).subscribe (
    (response) => {
      this.displaySendRaw = false;
      this.status = "Sent " + bufView.length + " bytes to interface " + this.selectedInterface;
    },
    (error) => {
      this.displaySendRaw = false;
      this.displayError("sending raw data", error, true);
    });
  }

  sendRawCmd(event) {
  
    var self = this;
    var reader = new FileReader();
    reader.onload = function(e) {
      self.onLoad(e);
    }
    reader.onerror = function(e) {
      self.displaySendRaw = false;
      var target:any = e.target;
      self.displayError("sending raw data", target.error, true);
    }
    // TBD - use the other event handlers to implement a progress bar for the 
    // file upload.  Handle abort as well?
    //reader.onloadstart = function(e) {}
    //reader.onprogress = function(e) {}
    //reader.onloadend = function(e) {}
    //reader.onabort = function(e) {}

    reader.readAsArrayBuffer(this.rawCmdFile);
  }

  cancelRawCmd(event) {
    this.displaySendRaw = false;
    this.status = 'Raw command not sent';
  }
}

<div class="container" style="margin-top:20px;margin-bottom:20px;">
  <h2>Command Sender</h2>
  <p-menubar [model]="menuItems"></p-menubar>
  <p style="margin-top:10px;">
    <cosmos-target-command-chooser (onSet)="commandChanged($event)" (onCmdSent)="sendCmd($event)" (onStatusChange)="statusChange($event)" [disabled]="sendDisabled"></cosmos-target-command-chooser>
  </p>

  <p *ngIf="rows.length!=0">Parameters:</p>
  <p-dataTable #dt *ngIf="rows.length!=0" [value]="rows" [editable]="true" scrollable="true" scrollHeight="600px">
    <p-column field="parameter_name" [style]="{'width':'20%', 'text-align':'right', 'word-break':'break-all'}" [editable]="false">
      <ng-template pTemplate="header"><div style="text-align:center">Name</div></ng-template>
    </p-column>
    <p-column field="val_and_states" [style]="{'width':'25%', 'text-align':'right', 'word-break':'break-all'}" [editable]="true">
      <ng-template pTemplate="header"><div style="text-align:center">Value or State</div></ng-template>
      <ng-template let-col let-rowIndex="rowIndex" let-rowData="rowData" pTemplate="editor">
        <command-parameter-editor [(ngModel)]="rowData[col.field]" (keydown)="dt.onCellEditorKeydown($event, col, rowData, rowIndex)"></command-parameter-editor>
      </ng-template>
      <ng-template let-col let-rowIndex="rowIndex" let-rowData="rowData" pTemplate="body">
        <command-parameter-body [value]="rowData[col.field]"></command-parameter-body>
      </ng-template>
    </p-column>
    <p-column field="units" [style]="{'width':'10%', 'text-align':'right', 'word-break':'break-all'}" [editable]="false">
      <ng-template pTemplate="header"><div style="text-align:center">Units</div></ng-template>
    </p-column>
    <p-column field="description" [style]="{'width':'45%', 'text-align':'left', 'word-break':'break-all'}" [editable]="false">
      <ng-template pTemplate="header"><div style="text-align:center">Description</div></ng-template>
    </p-column>
  </p-dataTable>

  <p *ngIf="status != ''">Status: {{status}}</p>

</div>

<p-dialog header="Error" [(visible)]="displayErrorDialog" modal=true>
  <label>{{status}}</label>
  <div align="center">
     <button pButton type="button" (click)="ackError()" label="Ok"></button>
  </div>
</p-dialog>

<p-dialog header="Hazardous Command" [(visible)]="displaySendHazardous" modal=true>
  <label>Warning: Command {{targetName}} {{commandName}} is Hazardous.  Send?</label>
  <div align="center">
     <button pButton type="button" (click)="sendHazardousCmd()" label="Yes"></button>
     <button pButton type="button" (click)="cancelHazardousCmd()" label="No"></button>
  </div>
</p-dialog>

<p-dialog header="Send Raw Data From File" [(visible)]="displaySendRaw" [width]="400" modal=true>
  <div>
     <label>Interface: </label>
     <p-dropdown [options]="interfaces" [(ngModel)]="selectedInterface" [style]="{'width':'200px'}" appendTo="body"></p-dropdown>
  </div>
  <div style="float:left;width:100%;">
     <label style="float:left;">Filename: </label>
     <input type="file" (change)="selectRawCmdFile($event)" style="float:left">
  </div>
  <div align="center">
     <button pButton type="button" (click)="cancelRawCmd()" label="Cancel"></button>
     <button pButton type="button" (click)="sendRawCmd()" label="Ok"></button>
  </div>
</p-dialog>

// web/frontend/src/tools/CommandSender/CommandSender.vue
<template>
  <div>
    <app-nav app :menus="menus" />
    <TargetPacketItemChooser
      :initialTargetName="this.$route.params.target"
      :initialPacketName="this.$route.params.packet"
      @on-set="commandChanged($event)"
      @click="sendCmd($event)"
      :disabled="sendDisabled"
      buttonText="Send"
      mode="cmd"
    ></TargetPacketItemChooser>

    <v-card v-if="rows.length != 0">
      <v-card-title>
        Parameters
        <v-spacer></v-spacer>
        <v-text-field
          v-model="search"
          append-icon="mdi-magnify"
          label="Search"
          single-line
          hide-details
        ></v-text-field>
      </v-card-title>
      <v-data-table
        :headers="headers"
        :items="rows"
        :search="search"
        calculate-widths
        disable-pagination
        hide-default-footer
        multi-sort
        dense
        @contextmenu:row="showContextMenu"
      >
        <template v-slot:item.val_and_states="{ item }">
          <CommandParameterEditor v-model="item.val_and_states" :statesInHex="statesInHex"></CommandParameterEditor>
        </template>
      </v-data-table>
    </v-card>
    <p v-if="status != ''">Status: {{ status }}</p>

    <v-menu v-model="contextMenuShown" :position-x="x" :position-y="y" absolute offset-y>
      <v-list>
        <v-list-item
          v-for="(item, index) in contextMenuOptions"
          :key="index"
          @click.stop="item.action"
        >
          <v-list-item-title>{{ item.title }}</v-list-item-title>
        </v-list-item>
      </v-list>
    </v-menu>
    <DetailsDialog
      :targetName="targetName"
      :packetName="commandName"
      :itemName="parameterName"
      :type="'cmd'"
      v-model="viewDetails"
    />

    <v-dialog v-model="displayErrorDialog" max-width="300">
      <v-card class="pa-3">
        <v-card-title class="headline">Error</v-card-title>
        <v-card-text>{{ status }}</v-card-text>
        <v-btn color="primary" @click="displayErrorDialog = false">Ok</v-btn>
      </v-card>
    </v-dialog>

    <v-dialog v-model="displaySendHazardous" max-width="300">
      <v-card class="pa-3">
        <v-card-title class="headline">Hazardous</v-card-title>
        <v-card-text>
          Warning: Command {{ targetName }} {{ commandName }} is Hazardous.
          Send?
        </v-card-text>
        <v-btn @click="sendHazardousCmd" class="primary mr-4">Yes</v-btn>
        <v-btn @click="cancelHazardousCmd" class="primary">No</v-btn>
      </v-card>
    </v-dialog>

    <v-dialog v-model="displaySendRaw" max-width="400">
      <v-card>
        <v-card-title class="headline">Send Raw</v-card-title>
        <v-container>
          <v-row no-gutters>
            <v-col>Interface:</v-col>
            <v-col>
              <v-select
                solo
                hide-details
                dense
                :items="interfaces"
                item-text="label"
                item-value="value"
                v-model="selectedInterface"
              ></v-select>
            </v-col>
          </v-row>
          <v-row no-gutters>
            <v-col>Filename:</v-col>
            <v-col>
              <input type="file" @change="selectRawCmdFile($event)" />
            </v-col>
          </v-row>
          <v-row>
            <v-col>
              <v-btn @click="cancelRawCmd" class="primary" block>Cancel</v-btn>
            </v-col>
            <v-col>
              <v-btn @click="sendRawCmd" class="primary" block>Ok</v-btn>
            </v-col>
          </v-row>
        </v-container>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
import AppNav from '@/AppNav'
import TargetPacketItemChooser from '@/components/TargetPacketItemChooser'
import CommandParameterEditor from '@/tools/CommandSender/CommandParameterEditor'
import { CosmosApi } from '@/services/cosmos-api'
import DetailsDialog from '@/components/DetailsDialog'
import 'sprintf-js'
export default {
  components: {
    AppNav,
    DetailsDialog,
    TargetPacketItemChooser,
    CommandParameterEditor
  },
  data() {
    return {
      search: '',
      headers: [
        { text: 'Name', value: 'parameter_name' },
        { text: 'Value or State', value: 'val_and_states' },
        { text: 'Units', value: 'units' },
        { text: 'Description', value: 'description' }
      ],
      targetName: '',
      commandName: '',
      ignoreRangeChecks: false,
      statesInHex: false,
      showIgnoredParams: false,
      cmdRaw: false,
      ignoredParams: [],
      rows: [],
      interfaces: [],
      selectedInterface: '',
      rawCmdFile: null,
      status: '',
      displaySendHazardous: false,
      displayErrorDialog: false,
      displaySendRaw: false,
      sendDisabled: true,
      api: null,
      viewDetails: false,
      contextMenuShown: false,
      parameterName: '',
      x: 0,
      y: 0,
      contextMenuOptions: [
        {
          title: 'Details',
          action: () => {
            this.contextMenuShown = false
            this.viewDetails = true
          }
        }
      ],
      menus: [
        {
          label: 'File',
          items: [
            {
              label: 'Send Raw',
              command: () => {
                this.setupRawCmd()
              }
            }
          ]
        },
        {
          label: 'Mode',
          items: [
            {
              label: 'Ignore Range Checks',
              checkbox: true,
              command: () => {
                this.ignoreRangeChecks = !this.ignoreRangeChecks
              }
            },
            {
              label: 'Display State Values in Hex',
              checkbox: true,
              command: () => {
                this.statesInHex = !this.statesInHex
              }
            },
            {
              label: 'Show Ignored Parameters',
              checkbox: true,
              command: () => {
                this.showIgnoredParams = !this.showIgnoredParams
                // TODO: Maybe we don't need to do this if the data-table
                // can render the whole thing and we just display with v-if
                this.updateCmdParams()
              }
            },
            {
              label: 'Disable Parameter Conversions',
              checkbox: true,
              command: () => {
                this.cmdRaw = !this.cmdRaw
              }
            }
          ]
        }
      ]
    }
  },
  methods: {
    showContextMenu(e, row) {
      e.preventDefault()
      this.parameterName = row.item.parameter_name
      this.contextMenuShown = false
      this.x = e.clientX
      this.y = e.clientY
      this.$nextTick(() => {
        this.contextMenuShown = true
      })
    },
    isFloat(str) {
      // Regex to identify a string as a floating point number
      if (/^\s*[-+]?\d*\.\d+\s*$/.test(str)) {
        return true
      }
      // Regex to identify a string as a floating point number in scientific notation.
      if (/^\s*[-+]?(\d+((\.\d+)?)|(\.\d+))[eE][-+]?\d+\s*$/.test(str)) {
        return true
      }
      return false
    },

    isInt(str) {
      // Regular expression to identify a String as an integer
      if (/^\s*[-+]?\d+\s*$/.test(str)) {
        return true
      }

      // # Regular expression to identify a String as an integer in hexadecimal format
      if (/^\s*0[xX][\dabcdefABCDEF]+\s*$/.test(str)) {
        return true
      }
      return false
    },

    isArray(str) {
      // Regular expression to identify a String as an Array
      if (/^\s*\[.*\]\s*$/.test(str)) {
        return true
      }
      return false
    },

    removeQuotes(str) {
      // Return the string with leading and trailing quotes removed
      if (str.length < 2) {
        return str
      }
      var firstChar = str.charAt(0)
      if (firstChar != '"' && firstChar != "'") {
        return str
      }
      var lastChar = str.charAt(str.length - 1)
      if (firstChar != lastChar) {
        return str
      }
      return str.slice(1, -1)
    },

    convertToValue(param) {
      if (typeof param.val_and_states.val != 'string') {
        return param.val_and_states.val
      }

      var str = param.val_and_states.val
      var quotes_removed = this.removeQuotes(str)
      if (str == quotes_removed) {
        var upcaseStr = str.toUpperCase()

        if (
          (param.type == 'STRING' || param.type == 'BLOCK') &&
          upcaseStr.startsWith('0X')
        ) {
          var hexStr = upcaseStr.slice(2)
          if (hexStr.length % 2 != 0) {
            hexStr = '0' + hexStr
          }
          var jstr = { json_class: 'String', raw: [] }
          for (var i = 0; i < hexStr.length; i += 2) {
            var nibble = hexStr.charAt(i) + hexStr.charAt(i + 1)
            jstr.raw.push(parseInt(nibble, 16))
          }
          return jstr
        } else {
          if (upcaseStr == 'INFINITY') {
            return Infinity
          } else if (upcaseStr == '-INFINITY') {
            return -Infinity
          } else if (upcaseStr == 'NAN') {
            return NaN
          } else if (this.isFloat(str)) {
            return parseFloat(str)
          } else if (this.isInt(str)) {
            return parseInt(str)
          } else if (this.isArray(str)) {
            return eval(str)
          } else {
            return str
          }
        }
      } else {
        return quotes_removed
      }
    },

    convertToString(value) {
      var i = 0
      var return_value = ''
      if (Object.prototype.toString.call(value).slice(8, -1) === 'Array') {
        var arrayLength = value.length
        return_value = '[ '
        for (i = 0; i < arrayLength; i++) {
          if (
            Object.prototype.toString.call(value[i]).slice(8, -1) === 'String'
          ) {
            return_value += '"' + value[i] + '"'
          } else {
            return_value += value[i]
          }
          if (i != arrayLength - 1) {
            return_value += ', '
          }
        }
        return_value += ' ]'
      } else if (
        Object.prototype.toString.call(value).slice(8, -1) === 'Object'
      ) {
        if (value.json_class == 'String' && value.raw) {
          // This is binary data, display in hex.
          return_value = '0x'
          for (i = 0; i < value.raw.length; i++) {
            var nibble = value.raw[i].toString(16).toUpperCase()
            if (nibble.length < 2) {
              nibble = '0' + nibble
            }
            return_value += nibble
          }
        } else if (value.json_class == 'Float' && value.raw) {
          return_value = value.raw
        } else {
          // TBD - are there other objects that we need to handle?
          return_value = String(value)
        }
      } else {
        return_value = String(value)
      }
      return return_value
    },

    commandChanged(event) {
      if (
        this.targetName === event.targetName &&
        this.packetName === event.packetName
      ) {
        return
      }
      this.targetName = event.targetName
      this.commandName = event.packetName
      if (
        this.$route.params.target != this.targetName &&
        this.$route.params.packet != this.packetName
      ) {
        this.$router.push({
          name: 'CommandSender',
          params: {
            target: this.targetName,
            packet: this.commandName
          }
        })
      }
      this.updateCmdParams()
    },

    updateCmdParams() {
      this.sendDisabled = true
      this.ignoredParams = []
      this.rows = []
      this.api.get_target_ignored_parameters(this.targetName).then(
        ignoredParams => {
          this.ignoredParams = ignoredParams
          this.api.get_command(this.targetName, this.commandName).then(
            command => {
              command.items.forEach(parameter => {
                if (
                  !this.ignoredParams.includes(parameter.name) ||
                  this.showIgnoredParams
                ) {
                  let val = parameter.default
                  if (parameter.required) {
                    val = ''
                  }
                  if (parameter.format_string) {
                    val = sprintf(parameter.format_string, parameter.default)
                  }
                  this.rows.push({
                    parameter_name: parameter.name,
                    val_and_states: {
                      val: val,
                      states: parameter.states,
                      selected_state: null,
                      selected_state_label: '',
                      manual_value: null
                    },
                    description: parameter.description,
                    units: parameter.units,
                    type: parameter.data_type
                  })
                }
              })
              this.sendDisabled = false
              this.status = ''
            },
            error => {
              this.displayError('getting command parameters', error)
            }
          )
        },
        error => {
          this.displayError('getting ignored parameters', error)
        }
      )
    },

    statusChange(event) {
      this.status = event.status
    },

    sendCmd() {
      let paramList = {}
      for (var i = 0; i < this.rows.length; i++) {
        paramList[this.rows[i].parameter_name] = this.convertToValue(
          this.rows[i]
        )
      }

      let hazardous = false
      let cmd = ''
      this.api
        .get_cmd_hazardous(this.targetName, this.commandName, paramList)
        .then(
          response => {
            hazardous = response

            if (hazardous) {
              this.displaySendHazardous = true
            } else {
              let obs
              if (this.cmdRaw) {
                if (this.ignoreRangeChecks) {
                  cmd = 'cmd_raw_no_range_check'
                  obs = this.api.cmd_raw_no_range_check(
                    this.targetName,
                    this.commandName,
                    paramList
                  )
                } else {
                  cmd = 'cmd_raw'
                  obs = this.api.cmd_raw(
                    this.targetName,
                    this.commandName,
                    paramList
                  )
                }
              } else {
                if (this.ignoreRangeChecks) {
                  cmd = 'cmd_no_range_check'
                  obs = this.api.cmd_no_range_check(
                    this.targetName,
                    this.commandName,
                    paramList
                  )
                } else {
                  cmd = 'cmd'
                  obs = this.api.cmd(
                    this.targetName,
                    this.commandName,
                    paramList
                  )
                }
              }

              obs.then(
                response => {
                  this.processCmdResponse(true, cmd, response)
                },
                error => {
                  console.log(error)
                  this.processCmdResponse(false, cmd, error)
                }
              )
            }
          },
          error => {
            this.processCmdResponse(false, cmd, error)
          }
        )
    },

    sendHazardousCmd() {
      this.displaySendHazardous = false
      var paramList = {}
      for (var i = 0; i < this.rows.length; i++) {
        paramList[this.rows[i].parameter_name] = this.convertToValue(
          this.rows[i]
        )
      }

      let obs = ''
      let cmd = ''
      if (this.cmdRaw) {
        if (this.ignoreRangeChecks) {
          cmd = 'cmd_no_checks'
          obs = this.api.cmd_raw_no_checks(
            this.targetName,
            this.commandName,
            paramList
          )
        } else {
          cmd = 'cmd_no_hazardous_check'
          obs = this.api.cmd_raw_no_hazardous_check(
            this.targetName,
            this.commandName,
            paramList
          )
        }
      } else {
        if (this.ignoreRangeChecks) {
          cmd = 'cmd_no_checks'
          obs = this.api.cmd_no_checks(
            this.targetName,
            this.commandName,
            paramList
          )
        } else {
          cmd = 'cmd_no_hazardous_check'
          obs = this.api.cmd_no_hazardous_check(
            this.targetName,
            this.commandName,
            paramList
          )
        }
      }

      obs.then(
        response => {
          this.processCmdResponse(true, cmd, response)
        },
        error => {
          this.processCmdResponse(false, cmd, error)
        }
      )
    },

    cancelHazardousCmd() {
      this.displaySendHazardous = false
      this.status = 'Hazardous command not sent'
    },

    processCmdResponse(cmd_sent, cmd, response) {
      var msg = ''
      if (cmd_sent) {
        msg += cmd + '("' + response[0] + ' ' + response[1]
        var keys = Object.keys(response[2])
        if (keys.length > 0) {
          msg += ' with '
          for (var i = 0; i < keys.length; i++) {
            var key = keys[i]
            msg += key + ' ' + this.convertToString(response[2][key])
            if (i < keys.length - 1) {
              msg += ', '
            }
          }
        }
        msg += '") sent.'

        this.status = msg
      } else {
        var context = 'sending ' + this.targetName + ' ' + this.commandName
        this.displayError(context, response, true)
      }
    },

    displayError(context, error, showDialog = false) {
      this.status = 'Error ' + context + ' due to ' + error.name
      if (error.message && error.message != '') {
        this.status += ': '
        this.status += error.message
      }
      if (showDialog) {
        this.displayErrorDialog = true
      }
    },

    setupRawCmd() {
      this.api.get_interface_names().then(
        response => {
          var interfaces = []
          for (var i = 0; i < response.length; i++) {
            interfaces.push({ label: response[i], value: response[i] })
          }
          this.interfaces = interfaces
          this.selectedInterface = interfaces[0].value
          this.displaySendRaw = true
        },
        error => {
          this.displaySendRaw = false
          this.displayError('getting interface names', error, true)
        }
      )
    },

    selectRawCmdFile(event) {
      this.rawCmdFile = event.target.files[0]
    },

    onLoad(event) {
      var bufView = new Uint8Array(event.target.result)
      var jstr = { json_class: 'String', raw: [] }
      for (var i = 0; i < bufView.length; i++) {
        jstr.raw.push(bufView[i])
      }

      this.api.send_raw(this.selectedInterface, jstr).then(
        () => {
          this.displaySendRaw = false
          this.status =
            'Sent ' +
            bufView.length +
            ' bytes to interface ' +
            this.selectedInterface
        },
        error => {
          this.displaySendRaw = false
          this.displayError('sending raw data', error, true)
        }
      )
    },

    sendRawCmd() {
      var self = this
      var reader = new FileReader()
      reader.onload = function(e) {
        self.onLoad(e)
      }
      reader.onerror = function(e) {
        self.displaySendRaw = false
        var target = e.target
        self.displayError('sending raw data', target.error, true)
      }
      // TBD - use the other event handlers to implement a progress bar for the
      // file upload.  Handle abort as well?
      //reader.onloadstart = function(e) {}
      //reader.onprogress = function(e) {}
      //reader.onloadend = function(e) {}
      //reader.onabort = function(e) {}

      reader.readAsArrayBuffer(this.rawCmdFile)
    },

    cancelRawCmd() {
      this.displaySendRaw = false
      this.status = 'Raw command not sent'
    }
  },
  created() {
    this.api = new CosmosApi()
  }
}
</script>

<style scoped></style>
